const users = require('../routes/users');
const menus = require('../routes/menus');
const employees = require('../routes/employees');
const customer = require('../routes/customer');
const staff = require('../routes/staff');
const Association = require('../routes/association');
const Disbursement = require('../routes/disbursement');
const Product = require('../routes/product');
const Bank = require('../routes/bank');
const BankAccount = require('../routes/bankAccount');
const Holiday = require('../routes/holiday');
const Branch = require('../routes/branch');
const ExpensesItem = require('../routes/expensesItem');
const Vault = require('../routes/vault');
const Expenses = require('../routes/expenses');
const CashAccounting = require('../routes/cashAccounting');
const IssuedLoanCheques = require('../routes/issuedLoanCheques');
const LoanBooking = require('../routes/loanBooking');
const BulkCash = require('../routes/bulkCashReceipt');
const DailyCollections = require('../routes/dailyCollections');
const LoanReport = require('../routes/loanReports');
const BankTrans = require('../routes/bankTrans');
const Backup = require('../routes/backup');
const Investment = require('../routes/investment');
const Withdrawal = require('../routes/bankWithdrawals');
const UserRoles = require('../routes/userRoles');
const UserAccess = require('../routes/userAccess');

const RegistrationFee = require('../routes/registrationFee');
const CashCollateral = require('../routes/cashCollateral');
const User = require('../routes/users');
const Auth = require('../routes/auth');
const express = require('express');
const cors = require('cors');
const app = express();
// const router = express.Router();

const apiPrefix = 'api';

module.exports = function (app) {
	app.use(express.urlencoded({ extended: true }));
	app.use(express.json());
	app.use(cors());
	app.use('/' + apiPrefix + '/users', users);
	app.use('/' + apiPrefix + '/menus', menus);
	app.use('/api/menus', menus);
	app.use('/api/employees', employees);
	app.use('/api/customer', customer);
	app.use('/api/setup/staff', staff);
	app.use('/api/setup/association', Association);
	app.use('/api/setup/product', Product);
	app.use('/api/setup/bank', Bank);
	app.use('/api/setup/bankaccount', BankAccount);
	app.use('/api/setup/holiday', Holiday);
	app.use('/api/setup/branch', Branch);
	app.use('/api/setup/expensesitem', ExpensesItem);
	app.use('/api/setup/user', User);
	app.use('/api/setup/userroles', UserRoles);
	app.use('/api/setup/useraccess', UserAccess);
	app.use('/api/auth', Auth);
	app.use('/api/loan/issuedloancheques', IssuedLoanCheques);
	app.use('/api/loan/disburse', Disbursement);
	app.use('/api/loan/registrationfee', RegistrationFee);
	app.use('/api/loan/cashcollateral', CashCollateral);
	app.use('/api/loan/booking', LoanBooking);
	app.use('/api/loan/bulkcash', BulkCash);
	app.use('/api/loan/dailycollections', DailyCollections);
	app.use('/api/transaction/expenses', Expenses);
	app.use('/api/cashaccounting', CashAccounting);
	app.use('/api/vault', Vault);
	app.use('/api/loanreports', LoanReport);
	app.use('/api/banktrans', BankTrans);
	app.use('/api/backup', Backup);
	app.use('/api/investment', Investment);
	app.use('/api/withdrawals', Withdrawal);
};
